spring:
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false

  datasource:
    url: jdbc:mysql://localhost:3306/mesce?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true