version: 2.1

orbs:
  docker: circleci/docker@1.5.0

executors:
 docker-executor:
   docker:
     - image: circleci/openjdk:11.0.3-jdk-stretch


commands:
  restore_cache_cmd:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
  save_cache_cmd:
    steps:
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
  # test:
  #   steps:
  #     - checkout
  #     - restore_cache_cmd
  #     - run: ./mvnw test
  #     - save_cache_cmd
  build:
    steps:
      - checkout
      - restore_cache_cmd
      - run: ./mvnw -Dmaven.test.skip=true package
      - save_cache_cmd
  build-image:
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: masouza/mesce
      - docker/push:
          digest-path: /tmp/digest.txt
          image: masouza/mesce
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"


jobs:
  # test-with-docker:
  #   executor: docker-executor
  #   steps:
  #     - test
  build-with-docker:
    executor: docker-executor
    steps:
      - build
  build-and-push:
    executor: docker/docker
    steps:
        - build-image
    


workflows:
  build-then-test-with-docker:
    jobs:
      - build-with-docker
      # - test-with-docker:
      #     requires:
      #       - build-with-docker
      - build-and-push:
          requires:
            - build-with-docker
